services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    blog.uploader:
        class: BlogBundle\Services\FileUploader
        # '%kernel.project_dir%/web/uploads/images'
        arguments: ['%upload_directory%']