BlogBundle\Entity\Picture:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\PictureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        src:
            type: string
            length: 255
        alt:
            type: string
            length: 255

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        postPersist: [ upload ]
        postRemove: [ remove ]
        preRemove: [ preRemove ]
